kotlin.code.style=official

GROUP=dev.andrewohara
VERSION_NAME=latest-SNAPSHOT
POM_DESCRIPTION=Collection of useful kotlin microservice utilities
POM_URL=https://github.com/oharaandrew314/service-utils
POM_SCM_URL=https://github.com/oharaandrew314/service-utils
POM_SCM_CONNECTION=scm:git:git://github.com/oharaandrew314/service-utils.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/oharaandrew314/service-utils.git
POM_LICENCE_NAME=The Apache Software License, Version 2.0
POM_LICENCE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENCE_DIST=repo
POM_DEVELOPER_ID=oharaandrew314
POM_DEVELOPER_NAME=Andrew O'Hara
SONATYPE_HOST=CENTRAL_PORTAL
SONATYPE_STAGING_PROFILE=dev.andrewohara
RELEASE_SIGNING_ENABLED=true
SONATYPE_AUTOMATIC_RELEASE=true
POM_NAME=Service Utils
POM_ARTIFACT_ID=service-utils
POM_PACKAGING=jar