name: Main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v7

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin

      - name: Test
        run: sh ./gradlew check --info

  publish:
    needs: [ test ]
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin

      - name: Publish
        env:
          ORG_GRADLE_PROJECT_VERSION_NAME: ${{ github.event.release.tag_name }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.central_username }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.central_password }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.signing_key }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.signing_key_password }}
        run: sh ./gradlew publish --no-configuration-cache