name: Test modern LTS JDKs on all OS's

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin

      - name: Build Coverage
        run: sh ./gradlew check jacocoTestReport

      - name: Upload Coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java_version: [ 11, 17, 21 ]
        os: [windows-latest, macOS-latest, ubuntu-latest]
        distribution: [ temurin ]
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Set up ${{ matrix.distribution }} JDK ${{ matrix.java_version }} on ${{ matrix.os }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java_version }}
          distribution: ${{ matrix.distribution }}

      - name: Test
        run: sh ./gradlew check --stacktrace
  publish:
    needs: [ test, coverage ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin

      - name: Publish
        run: sh ./gradlew publish