name: Test JDK 21 on all OS's

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java_version: [ 21 ]
        os:
#          - windows-latest
#          - macOS-latest
          - ubuntu-latest
        distribution: [ temurin ]
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v7

      - name: Set up ${{ matrix.distribution }} JDK ${{ matrix.java_version }} on ${{ matrix.os }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java_version }}
          distribution: ${{ matrix.distribution }}

#      - name: Setup Docker
#        if: matrix.os != 'ubuntu-latest' # already available on linux
#        uses: docker/setup-docker-action@v5

      - name: Test
        run: sh ./gradlew check --info

  publish:
    needs: [ test ]
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin

#      - name: Setup Docker
#        if: matrix.os != 'ubuntu-latest'
#        uses: docker/setup-docker-action@v5 # already available on linux

      - name: Publish
        env:
          ORG_GRADLE_PROJECT_VERSION_NAME: ${{ github.event.release.tag_name }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.central_username }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.central_password }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.signing_key }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.signing_key_password }}
        run: sh ./gradlew publish --no-configuration-cache